#' Data Dictionary: sj_all_revenue
#'
#' The `dd_sj_all_revenue()` function generates a data dictionary based on the
#' `sj_all_revenue` table, which is available in the **intendo** package as
#' a dataset.
#'
#' @export
dd_sj_all_revenue <- function() {

  pointblank::create_informant(
    read_fn = ~ sj_all_revenue,
    label = "All revenue events for *Super Jetroid*",
    tbl_name = "sj_all_revenue"
  ) %>%
    pointblank::info_tabular(
      summary = "This summary table provides revenue data for every in-app
      purchase and ad view captured by our instrumentation in Super Jetroid.
      Details about the timing of the revenue event (`session_start` and
      `time` of earned revenue) are provided along with identifiers for the
      revenue source and some metadata for the player for segmentation
      purposes.",
      `each row is` = "A discrete revenue event for a player in a session.
      Details about the revenue source are provided for both IAPs and ad
      views. Some values intrinsic to the player (e.g., `country`) are
      provided for sake of convenience.",
      `data production` = "This table that is created three times a day
      at set times. The data for advertising events is delayed by three days
      because such information is pulled from our three advertising partners but
      one of them requires the extra time to have the revenue information
      available. Please visit our internal *Intendo* website to view status
      reports on delayed data. Data providers for IAPs occasionally revise the
      revenue amounts and adjust for refunds, so, revenue amounts can vary
      somewhat for up to 20 days back from the present day.",
      `person responsible` = "C. Ellefson: +1 (905) 329-3702,
      Central Engineering (((Toronto Downtown office)))"
    ) %>%
    pointblank::info_columns(
      columns = "player_id",
      info = "This is a unique identifier for a user/player.",
      details = "Always composed of 12 *uppercase* letters followed
      by 3 digits."
    ) %>%
    pointblank::info_columns(
      columns = "session_id",
      info = "The date (in the [[YYYY-MM-DD]]<<color: steelblue;>> format)
      that a player (with a `player_id`) logged into the game for *any amount
      of time*. Since this is a daily summary by player we expect dates and
      *not* date-time values.",
      details = "Note that dates are based on UTC time and not the player's
      local time. Also, sessions that carry on to the next day (in UTC time,
      again) are not double counted."
    ) %>%
    pointblank::info_columns(
      columns = "session_start",
      info = "The starting time of the session in which a revenue event
      occurred. This is a datetime value (in the [[YYYY-MM-DD hh-mm-ss]]
      <<color: steelblue;>> format) for when a player (with a `player_id`)
      logged into the game and is associated with a session that had at least
      one revenue event.",
      details = ""
    ) %>%
    pointblank::info_columns(
      columns = "time",
      info = "The time that the revenue event occurred.",
      details = "This is captured by the store SDK and transmitted to us at the
      moment of purchase initiation. However, some cancelled/failed
      transactions will still appear as a purchase. In later pipeline runs, this
      is corrected with store data. The incidence is this happening is
      generally quite low however."
    ) %>%
    pointblank::info_columns(
      columns = "item_type",
      info = "Either `\"iap\"` or `\"ad\"` which stand for in-app purchase (or
      IAP) and ad view. Each item type has a specific set of `item_name`s."
    ) %>%
    pointblank::info_columns(
      columns = "item_name",
      info = "A name that describes the ad type (always in the form `ad_`) or
      the IAP item (using the non-user-facing, in-store product name).",
      details = "The advertising-based item names are generally either clips,
      (distinguished by the length of the clip in seconds), a survey type
      (`\"ad_survey\"`), or a playable (`\"ad_playable\"`). The IAPs fall into
      three subtypes: (1) primary currency of `\"gold\" with **7** levels, (2)
      secondary currency of `\"gems\" with **5** levels, and (3) different
      `offer`s issued by the SAO engine (**5** levels). The higher the level,
      the higher the value and the corresponding cost. These names map directly
      to the store item names (both ITC and Play Store).`"
    ) %>%
    pointblank::info_columns(
      columns = "item_revenue",
      info = "The estimated USD revenue generated by the IAP or ad view.",
      details = "IAP item revenue amounts are estimated by item cost by region.
      While ad revenue is obtained from our advertising partners though their
      respective APIs, that data is not available in a granularity that matches
      up with ad view events. Therefore all single-event ad revenue amounts
      in this column are estimates."
    ) %>%
    pointblank::info_columns(
      columns = "session_duration",
      info = "The length of the session (in minutes) in which the revenue
      event took place."
    ) %>%
    pointblank::info_columns(
      columns = "start_day",
      info = "The day that the player was first seen (the first login day).",
      details = "When taking the difference in days between `session_start` and
      `start_day` we get the player age, which is important for cohorting
      metrics and segmentation."
    ) %>%
    pointblank::info_columns(
      columns = "acquisition",
      info = "A label that designates how/where the player was acquired."
    ) %>%
    pointblank::info_columns(
      columns = "country",
      info = "The country of the player. This location information is captured
      at first login and doesn't account for sessions/purchases in other
      countries though incidence of that must be rare."
    ) %>%
    pointblank::info_section(
      section_name = "Further Details",
      frequency = "Three times per day",
      `time of updates` = "At 09:00, 17:00, and 23:00 UTC",
      `inception` = "2014-11-25",
      revisions = c(
        " - (2015-01-28) improved the precision of the `time` value.",
        " - (2015-02-05) added the `acquisition` and `country` columns."
      )
    ) %>%
    pointblank::incorporate() %>%
    pointblank::get_informant_report(
      title = "Data Dictionary: `sj_all_revenue`"
    )
}
